version: "3.3"
services:
  redis:
    image: redis:latest
    restart: "no"
    container_name: redisX
    ports:
      - "6379:6379"
    volumes:
      - /data/redis/db:/data
    networks:
      - bluebell-net

  #  mongo:
  #    image: mongo:latest
  #    restart: "no"
  #    container_name: mongoX
  #    ports:
  #      - "27017:27017"
  #    volumes:
  #      - /data/mongo/db:/data/db

  mysql:
    image: mysql:latest
    restart: "no"
    container_name: mysqlX
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - LANG=C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql/db:/var/lib/mysql
    networks:
      - bluebell-net

  #  rabbitmq:
  #    image: rabbitmq:3.7.7-management
  #    restart: "no"
  #    container_name: rabbitmqX
  #    ports:
  #      - "5672:5672"
  #      - "15672:15672"
  #
  #  consul:
  #    image: consul:latest
  #    restart: "no"
  #    container_name: consulX
  #    ports:
  #      - "8500:8500"
  #    command: agent -dev -ui -client 0.0.0.0
  #
  #  nats:
  #    image: nats:latest
  #    restart: "no"
  #    container_name: natsX
  #    ports:
  #      - "4222:4222"
  #      - "8222:8222"
  #    command: -m 8222
  #
  #  elastic:
  #    image: elasticsearch:7.6.2
  #    container_name: elasticX
  #    restart: "no"
  #    ports:
  #      - 9200:9200
  #      - 9300:9300
  #    environment:
  #      - "discovery.type=single-node"
  #      - "cluster.name=elasticsearch"
  #      volumes:
  #        - /data/elasticsearch/plugins:/usr/share/elasticsearch/plugins
  #        - /data/elasticsearch/data:/usr/share/elasticsearch/data
  #
  #  kibana:
  #    image: kibana:7.6.2
  #    container_name: kibanaX
  #    restart: "no"
  #    ports:
  #      - 5601:5601
  #    depends_on:
  #      - elastic
  #    links:
  #      - elasticX:es
  #    environment:
  #      - "elasticsearch.hosts=http://es:9200"
  bluebell:
    image: gzltommy/bluebell:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bluebellX
    restart: "no"
    depends_on:
      - mysql
      - redis
    ports:
      - "8081:8081"
    volumes:
      - /home/gzl/projects/test_dir/bluebell/conf/:/app/conf/ #映射配置文件
      - /home/gzl/projects/test_dir/bluebell/logs:/app/logs/ #映射日志文件
    networks:
      - bluebell-net
    command: sh -c "./wait-for.sh mysql:3306 redis:6379 -- ./bluebell -f ./conf/config.yaml"


networks:
  bluebell-net:
    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.25.255.0/24
#      driver: default