app_name: "bluebell"
# dev/release/test
mode: "dev"
port: 8081
version: "0.1.0.1"
limit_connection: 2000
start_time: "2022-07-27"
machine_id: 1
PPROF: 1

auth:
  jwt_secret: "ssajfoi10"
  # 单位 s
  jwt_expire: 3600

log:
  level: "debug"
  filename: "./logs/bluebell.log"
  max_siz: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "mysql" # 因为我们在项目中使用了 docker-compose 来部署服务，并且服务使用同一个 networks 参数，可以通过主机名（即 docker-compose 的服务名称）访问
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "redis"    # 因为我们在项目中使用了 docker-compose 来部署服务，并且服务使用同一个 networks 参数，可以通过主机名（即的服务名称）访问
  port: 6379
  password: ""
  db: 0
  pool_size: 100