app_name: "bluebell"
# dev/release/test
mode: "dev"
port: 8081
version: "0.1.0.1"
limit_connection: 2000
start_time: "2022-07-27"
machine_id: 1
PPROF: 1

auth:
  jwt_secret: "ssajfoi10"
  # 单位 s
  jwt_expire: 3600

log:
  level: "debug"
  filename: "./logs/bluebell.log"
  max_siz: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "192.168.24.133"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "test"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "192.168.24.133"
  port: 6379
  password: ""
  db: 0
  pool_size: 100